import { useMemo, useState } from "react";
import type { Place } from "../types";
import { PlaceCard } from "./PlaceCard";
import { RouteDialog } from "./RouteDialog";
import { applyDispositionBatch, groupedTripIds, matchesTripFilter, restoreDispositions, snapshotDispositions, sortTripPlaces, stableReviewQueue, tripCounts, type DispositionSnapshot, type TripFilter, type TripSort } from "./our-trip";
import { reviewPresentation, setDisposition, setPriority, setVote, type ReviewStore } from "./review";

type Props={places:Place[];store:ReviewStore;hasAuthoredPlan:boolean;onCommit:(store:ReviewStore)=>boolean;onOpen:(id:string)=>void;onExplore:()=>void;onAnalysis:()=>void;onPlanner:()=>void};
const filters:TripFilter[]=["Todos","Ambos","Fernando","Ella","Pendientes","Descartados"];
const moreFilters:TripFilter[]=["Ninguno","Gustos diferentes"];

export function OurTrip({places,store,hasAuthoredPlan,onCommit,onOpen,onExplore,onAnalysis,onPlanner}:Props){
 const [view,setView]=useState<"Intereses"|"Planificar"|"Dónde alojarnos">("Intereses");const [filter,setFilter]=useState<TripFilter>("Todos");const [sort,setSort]=useState<TripSort>("recommendation");
 const [selecting,setSelecting]=useState(false);const [selected,setSelected]=useState<Set<string>>(new Set());const [confirm,setConfirm]=useState<"shortlisted"|"discarded"|null>(null);const [undo,setUndo]=useState<DispositionSnapshot|null>(null);const [queue,setQueue]=useState<string[]|null>(null);const [queueIndex,setQueueIndex]=useState(0);
 const byId=useMemo(()=>new Map(places.map(p=>[p.id,p])),[places]);const counts=tripCounts(store);
 const filtered=useMemo(()=>sortTripPlaces(places.filter(p=>store.places[p.id]&&matchesTripFilter(store.places[p.id],filter)),store,sort),[places,store,filter,sort]);
 const groups=useMemo(()=>groupedTripIds(places,store,sort),[places,store,sort]);const shortlist=useMemo(()=>sortTripPlaces(places.filter(p=>store.places[p.id]?.disposition==="shortlisted"),store,sort),[places,store,sort]);
 const toggle=(id:string)=>setSelected(old=>{const n=new Set(old);if(n.has(id))n.delete(id);else n.add(id);return n;});
 const doBatch=()=>{if(!confirm)return;const ids=[...selected];const before=snapshotDispositions(store,ids);if(onCommit(applyDispositionBatch(store,ids,confirm))){setUndo(before);setConfirm(null);setSelected(new Set());setSelecting(false);}};
 const renderCard=(p:Place)=>{const r=store.places[p.id];const presentation=reviewPresentation(r.votes.fernando,r.votes.ella,r.inReviewQueue);return <div className="astra-trip-card" key={p.id} data-place-id={p.id}>{selecting&&<label className="astra-batch-check"><input type="checkbox" checked={selected.has(p.id)} onChange={()=>toggle(p.id)}/> Seleccionar {p.name}</label>}<PlaceCard place={p} saved={store.activeReviewer?r.votes[store.activeReviewer]==="yes":false} status={presentation.label} together={presentation.hearts===2} reviewerName={store.activeReviewer==="fernando"?"Fernando":store.activeReviewer==="ella"?"Ella":undefined} onToggle={()=>store.activeReviewer&&onCommit(setVote(store,p.id,store.activeReviewer,r.votes[store.activeReviewer]==="yes"?"unreviewed":"yes"))} onOpen={onOpen}/><details className="astra-trip-card__menu"><summary>Más acciones</summary><div>{store.activeReviewer&&<button onClick={()=>onCommit(setVote(store,p.id,store.activeReviewer!,"no"))}>Ahora no</button>}<label>Prioridad del viaje<select value={r.priority??"Por decidir"} onChange={e=>onCommit(setPriority(store,p.id,e.target.value as "Por decidir"|"Alta"|"Media"|"Baja"))}><option>Por decidir</option><option>Alta</option><option>Media</option><option>Baja</option></select></label><button onClick={()=>onCommit(setDisposition(store,p.id,"shortlisted"))}>Añadir a preselección</button><button onClick={()=>onCommit(setDisposition(store,p.id,"discarded"))}>Descartar del viaje</button></div></details></div>};
 const empty=filter==="Todos"?<div className="astra-empty"><h2>Su viaje empieza con un lugar</h2><button onClick={onExplore}>Explorar Japón</button></div>:filter==="Ambos"&&Object.values(store.places).some(r=>r.votes.fernando==="yes"||r.votes.ella==="yes")?<div className="astra-empty"><h2>Todavía no hay coincidencias. Revisen lo que le gusta al otro.</h2><button onClick={()=>{const q=stableReviewQueue(store);setQueue(q);setQueueIndex(0)}}>Ver pendientes</button></div>:filter==="Descartados"?<div className="astra-empty"><h2>No han descartado lugares.</h2></div>:<div className="astra-empty"><h2>Sin lugares en {filter}</h2><button onClick={()=>setFilter("Todos")}>Quitar filtros</button></div>;
 return <section className="astra-trip"><h1>Nuestro viaje</h1><p className="astra-trip__note">Primero elegimos lugares. Después armamos el recorrido.</p><div className="astra-trip__counts"><div><strong>{counts.both}</strong><span>Ambos</span></div><div><strong>{counts.pending}</strong><span>Por comparar</span></div></div><nav className="astra-trip__tabs" aria-label="Secciones de Nuestro viaje">{(["Intereses","Planificar","Dónde alojarnos"] as const).map(x=><button key={x} aria-pressed={view===x} onClick={()=>setView(x)}>{x}</button>)}</nav>
 {view==="Intereses"&&<><div className="astra-trip__toolbar"><div className="astra-trip__filters">{filters.map(x=><button key={x} aria-pressed={filter===x} onClick={()=>setFilter(x)}>{x}</button>)}<label>Más<select value={moreFilters.includes(filter)?filter:""} onChange={e=>e.target.value&&setFilter(e.target.value as TripFilter)}><option value="">Elegir</option>{moreFilters.map(x=><option key={x}>{x}</option>)}</select></label></div><label>Ordenar<select value={sort} onChange={e=>setSort(e.target.value as TripSort)}><option value="priority">Prioridad del viaje</option><option value="recommendation">Recomendación</option><option value="name">Nombre</option><option value="hub">Hub</option></select></label><button onClick={()=>{setSelecting(x=>!x);setSelected(new Set())}}>{selecting?"Salir de selección":"Seleccionar"}</button><button onClick={()=>{setQueue(stableReviewQueue(store));setQueueIndex(0)}}>Revisar pendientes</button></div>{selecting&&<div className="astra-batch-bar"><strong>{selected.size} seleccionados</strong><button disabled={!selected.size} onClick={()=>setConfirm("shortlisted")}>Preseleccionar</button><button disabled={!selected.size} onClick={()=>setConfirm("discarded")}>Descartar</button></div>}{filter==="Todos"?groups.map(g=>g.ids.length?<section key={g.label} className="astra-trip__group"><h2>{g.label}</h2><div className="astra-trip__grid">{g.ids.map(id=>byId.get(id)).filter((p):p is Place=>!!p).map(renderCard)}</div></section>:null):filtered.length?<div className="astra-trip__grid">{filtered.map(renderCard)}</div>:empty}</>}
 {view==="Planificar"&&<section className="astra-planning-bridge"><h2>Preselección</h2>{shortlist.length?<ul>{shortlist.map(p=><li key={p.id}>{p.name}</li>)}</ul>:<p>Preseleccionen lugares antes de ordenar el recorrido. El plan anterior, si existe, se conserva.</p>}<button onClick={onAnalysis}>Ver distribución y tiempos</button><p className="astra-trip__help">Los rangos corresponden a la visita. No incluye traslados.</p><button className="astra-trip__planner-action astra-trip__planner-action--primary" onClick={onPlanner}>{hasAuthoredPlan?"Continuar recorrido":"Construir recorrido"}</button></section>}
 {view==="Dónde alojarnos"&&<div className="astra-empty"><h2>Dónde alojarnos</h2><p>Esta entrada conservará las opciones de alojamiento del constructor actual. La comparación de zonas llegará en una fase posterior.</p><button onClick={onPlanner}>{hasAuthoredPlan?"Continuar recorrido":"Construir recorrido"}</button></div>}
 {queue&&<RouteDialog labelledBy="queue-title" onClose={()=>setQueue(null)} returnFocus={null} overlayClassName="astra-confirm" panelClassName="astra-confirm__panel"><h2 id="queue-title">Revisar pendientes</h2>{queue.length?(()=>{const id=queue[queueIndex];const p=byId.get(id);return <><p>{queueIndex+1} de {queue.length}</p><h3>{p?.name??id}</h3><p>Elige explícitamente una respuesta. Navegar no guarda votos.</p>{store.activeReviewer&&<><button onClick={()=>onCommit(setVote(store,id,store.activeReviewer!,"yes"))}>Quiero ir</button><button onClick={()=>onCommit(setVote(store,id,store.activeReviewer!,"no"))}>Ahora no</button></>}<button disabled={queueIndex===0} onClick={()=>setQueueIndex(i=>i-1)}>Anterior</button><button disabled={queueIndex===queue.length-1} onClick={()=>setQueueIndex(i=>i+1)}>Siguiente</button></>} )():<p>No hay pendientes.</p>}</RouteDialog>}
 {confirm&&<RouteDialog labelledBy="batch-title" onClose={()=>setConfirm(null)} returnFocus={null} overlayClassName="astra-confirm" panelClassName="astra-confirm__panel"><h2 id="batch-title">Confirmar {confirm==="shortlisted"?"preselección":"descarte"}</h2><p>{selected.size} lugares</p><details><summary>Revisar nombres</summary><ul>{[...selected].map(id=><li key={id}>{byId.get(id)?.name??id}</li>)}</ul></details><button onClick={()=>setConfirm(null)}>Cancelar</button><button onClick={doBatch}>Confirmar</button></RouteDialog>}{undo&&<div className="astra-toast" role="status">Cambios guardados <button onClick={()=>{if(onCommit(restoreDispositions(store,undo)))setUndo(null)}}>Deshacer</button></div>}</section>;
}
